logger:
  level: "${LOGGER_LEVEL}"
storage:
  type: "sql"
  dsn: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
  migrations_dir: "migrations"
http:
  host: "${CALENDAR_HTTP_HOST}"
  port: "${CALENDAR_HTTP_PORT}"
grpc:
  host: "${CALENDAR_GRPC_HOST}"
  port: "${CALENDAR_GRPC_PORT}"
