logger:
  level: "${LOGGER_LEVEL}"
storage:
  type: "sql"
  dsn: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}?sslmode=disable"
rabbitmq:
  url: "amqp://${RABBITMQ_DEFAULT_USER}:${RABBITMQ_DEFAULT_PASS}@${RABBITMQ_HOST}:${RABBITMQ_PORT}/"
  queue: "notifications"
scheduler:
  scan_interval: ${SCHEDULER_SCAN_INTERVAL}
  clean_interval: ${SCHEDULER_CLEAN_INTERVAL}
